service: fast-api-with-serverless
frameworkVersion: "3"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get

